# Generated by Django 2.0 on 2019-11-26 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('barriosolidario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='valid',
        ),
        migrations.AddField(
            model_name='newspost',
            name='user',
            field=models.ForeignKey(default=uuid.UUID('9781200a-4862-4daa-9231-a759c28d7ff7'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
