# Generated by Django 2.0 on 2019-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriosolidario', '0002_auto_20191126_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='helppost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
