# Generated by Django 2.0 on 2019-12-02 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barriosolidario', '0003_auto_20191126_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(),
        ),
    ]
